name: Release
on:
  push:
    branches:
      - master
jobs:
  release-github:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN_REGISTRY }}
        run: npm run publish